const allWorks = [
    {
        id:1,
        cover:"guangjiao.jpg",
        imgs:["g1.jpg","g2.jpg","g3.jpg"],
        title:"外贸展会视觉设计",
        cate:"brandEvent",
        desc:"主导集团全球食品展会设计，包括德国科隆、东京、泰国、纽约及春秋两季广交会。负责对接外贸部门梳理海外市场需求，形成设计Brief并交乙方公司执行，全程把控方案沟通与落地。展位历经三代迭代，确立以“熊猫文化”为核心的视觉语言，划分产品陈列、品牌矩阵、实力背书与互动试吃四大功能区，以中式美学融合商业功能，实现国际辨识度与品牌专业形象的双重提升。"
    },
    {
        id:2,
        cover:"kaoyu.jpg",
        imgs:["k1.jpg","k2.jpg","k3.jpg","k4.jpg","k5.jpg","k6.jpg","k7.jpg"],
        title:"烤鱼品牌新品发布会视觉",
        cate:"brandEvent",
        desc:"统筹“好人家”烤鱼新品发布会整体视觉设计，打破传统平面模式，将发布会现场打造成沉浸式市集摊位场景，让观众在互动中直接品尝产品。通过场景营造传递产品信息，创造记忆点与话题，以体验驱动品牌传播。全程对接需求方梳理设计Brief，把控视觉调性与落地执行，确保活动按时高质量交付。"
    },
    {
        id:3,
        cover:"huoguo.jpg",
        imgs:["h1.jpg","h2.jpg"],
        title:"火锅季主题发布会视觉",
        cate:"brandEvent",
        desc:"统筹“好人家”火锅j季新品发布会整体视觉设计，打破传统平面模式，将现场打造成沉浸式火锅店实景，以暖调灯光、木质桌椅和火锅细节还原围炉聚餐的烟火气。从邀请函、现场导视到菜品卡、拍照打卡点，全链路物料保持统一调性，强化品牌温度与专业感。全程主导设计Brief梳理与落地执行，确保从概念到交付完整闭环。"
    },
    {
        id:4,
        cover:"shengdan.jpg",
        imgs:["s1.jpg","s2.jpg","s3.jpg"],
        title:"1点点圣诞买赠活动",
        cate:"brandEvent",
        desc:"统筹1点点成都区及中区圣诞活动全案，以圣诞主题视觉统一线上线下画面，打造温暖治愈的节日氛围。礼赠周边推出4款马卡龙色系圣诞树及隐藏款白色麋鹿，将节日符号以品牌化方式呈现，从选品设计到供应商打样、到货全程跟进，激发用户收集欲望与社交分享，拉动节点销售。"
    },
    {
        id:5,
        cover:"kaixueji.jpg",
        imgs:["kai1.jpg","kai2.jpg","kai3.jpg","kai4.jpg"],
        title:"1点点开学季活动",
        cate:"brandEvent",
        desc:"统筹1点点成都区开学季活动全案，以黑板色系统一线上线下视觉画面，将“开学”场景感贯穿门店海报与线上传播物料。礼赠周边选用手机支架及1点点logo形状回形针，兼顾实用与品牌识别，从选品设计到供应商打样、到货全程跟进，拉动节点销售与年轻用户互动。"
    },
    {
        id:6,
        cover:"520huodong.jpg",
        imgs:["51.jpg","52.png","53.jpg"],
        title:"1点点520买赠活动",
        cate:"brandEvent",
        desc:"统筹1点点成都区520活动全案，以马卡龙色系统一线下视觉调性，营造节日甜蜜氛围。礼赠周边推出5款马卡龙色系雪克杯造型头绳，将品牌标志性器具转化为可携带的时尚单品，从选品设计到供应商打样、到货全程跟进，强化品牌记忆点与用户情感连接。"
    },
    {
        id:7,
        cover:"costco1.jpg",
        imgs:["c1.jpg"],
        title:"COSTCO",
        cate:"retailMaterial",
        desc:"COSTCO"
    },
    {
        id:8,
        cover:"hema.jpg",
        imgs:["h1.jpg"],
        title:"盒马帆布袋",
        cate:"retailMaterial",
        desc:"盒马帆布袋"
    },
    {
        id:9,
        cover:"kaoyushichang.jpg",
        imgs:["k1.jpg"],
        title:"烤鱼市场物料",
        cate:"retailMaterial",
        desc:"烤鱼市场物料"
    },
    {
        id:10,
        cover:"kahuoguo.jpg",
        imgs:["ka1.jpg"],
        title:"KA火锅物料",
        cate:"retailMaterial",
        desc:"KA火锅物料"
    },
    {
        id:11,
        cover:"kasuancaiyu.jpg",
        imgs:["h1.jpg"],
        title:"KA酸菜鱼物料",
        cate:"retailMaterial",
        desc:"KA酸菜鱼物料"
    },
    {
        id:12,
        cover:"yinpin.jpg",
        imgs:["h1.jpg"],
        title:"超人气饮品KT板",
        cate:"retailMaterial",
        desc:"超人气饮品KT板"
    },
    {
        id:13,
        cover:"niuyang.jpg",
        imgs:["h1.jpg"],
        title:"牛羊肉渠道物料",
        cate:"retailMaterial",
        desc:"牛羊肉渠道物料"
    },
    {
        id:14,
        cover:"jianpuzhai.jpg",
        imgs:["h1.jpg"],
        title:"柬埔寨超市广告",
        cate:"retailMaterial",
        desc:"柬埔寨超市广告"
    },
    {
        id:15,
        cover:"scyscwl.jpg",
        imgs:["h1.jpg"],
        title:"酸菜鱼市场物料",
        cate:"retailMaterial",
        desc:"酸菜鱼市场物料"
    },
    {
        id:16,
        cover:"xtlcjwl.jpg",
        imgs:["h1.jpg"],
        title:"鲜汤料春季物料",
        cate:"retailMaterial",
        desc:"鲜汤料春季物料"
    },
    {
        id:17,
        cover:"smmlxg.jpg",
        imgs:["h1.jpg"],
        title:"山姆麻辣香锅详情页",
        cate:"retailMaterial",
        desc:"山姆麻辣香锅详情页"
    },
    {
        id:18,
        cover:"smscy.jpg",
        imgs:["h1.jpg"],
        title:"山姆山茶油凉拌汁详情页",
        cate:"retailMaterial",
        desc:"山姆山茶油凉拌汁详情页"
    },
    {
        id:19,
        cover:"qsfbnny.jpg",
        imgs:["h1.jpg"],
        title:"七色纺保暖内衣系列陈列",
        cate:"retailMaterial",
        desc:"七色纺保暖内衣系列陈列"
    },
    {
        id:20,
        cover:"qsfxjcy.jpg",
        imgs:["h1.jpg"],
        title:"七色纺夏季成衣陈列",
        cate:"retailMaterial",
        desc:"七色纺夏季成衣陈列"
    },
    {
        id:21,
        cover:"qsfyz.jpg",
        imgs:["h1.jpg"],
        title:"七色纺泳装陈列",
        cate:"retailMaterial",
        desc:"七色纺泳装陈列"
    },
    {
        id:22,
        cover:"wxhbfm.jpg",
        imgs:["m1.jpg"],
        title:"微信红包封面",
        cate:"newMedia",
        desc:"微信红包封面"
    },
    {
        id:23,
        cover:"CNYhd.jpg",
        imgs:["m1.jpg"],
        title:"CNY活动",
        cate:"newMedia",
        desc:"CNY活动"
    },
    {
        id:24,
        cover:"hrjdt.jpg",
        imgs:["m1.jpg"],
        title:"好人家冬调推文",
        cate:"newMedia",
        desc:"好人家冬调推文"
    },
    {
        id:25,
        cover:"hrjhhg.jpg",
        imgs:["m1.jpg"],
        title:"好人家厚火锅活动推文",
        cate:"newMedia",
        desc:"好人家厚火锅活动推文"
    },
    {
        id:26,
        cover:"hrjblb.jpg",
        imgs:["m1.jpg"],
        title:"好人家拔萝卜活动推文",
        cate:"newMedia",
        desc:"好人家拔萝卜活动推文"
    },
    {
        id:27,
        cover:"syzhq.jpg",
        imgs:["m1.jpg"],
        title:"好人家私域中秋活动",
        cate:"newMedia",
        desc:"好人家私域中秋活动"
    },
    {
        id:28,
        cover:"sy51.jpg",
        imgs:["m1.jpg"],
        title:"好人家私域51活动",
        cate:"newMedia",
        desc:"好人家私域51活动"
    },
    {
        id:29,
        cover:"syshj.jpg",
        imgs:["m1.jpg"],
        title:"好人家私域双节活动",
        cate:"newMedia",
        desc:"好人家私域双节活动"
    },
    {
        id:30,
        cover:"syhyr.jpg",
        imgs:["m1.jpg"],
        title:"好人家私域会员日活动",
        cate:"newMedia",
        desc:"好人家私域会员日活动"
    },
    {
        id:31,
        cover:"syqdyj.jpg",
        imgs:["m1.jpg"],
        title:"好人家私域签到摇奖活动",
        cate:"newMedia",
        desc:"好人家私域签到摇奖活动"
    },
    {
        id:32,
        cover:"tws11.jpg",
        imgs:["c1.jpg"],
        title:"天味双11",
        cate:"brandCulture",
        desc:"天味双11"
    },
    {
        id:33,
        cover:"qsfrzsc.jpg",
        imgs:["c1.jpg"],
        title:"七色纺入职手册",
        cate:"brandCulture",
        desc:"七色纺入职手册"
    },
    {
        id:34,
        cover:"qsfdwtj.jpg",
        imgs:["c1.jpg"],
        title:"七色纺端午团建",
        cate:"brandCulture",
        desc:"七色纺端午团建"
    },
    {
        id:35,
        cover:"qsfxsbqk.jpg",
        imgs:["c1.jpg"],
        title:"七色纺销售部期刊",
        cate:"brandCulture",
        desc:"七色纺销售部期刊"
    },
    {
        id:36,
        cover:"1ddppt.jpg",
        imgs:["c1.jpg"],
        title:"1点点PPT模版",
        cate:"brandCulture",
        desc:"1点点PPT模版"
    },
    {
        id:37,
        cover:"1ddhb.jpg",
        imgs:["i1.jpg"],
        title:"1点点红包插画",
        cate:"illustration",
        desc:"1点点红包插画"
    },
    {
        id:38,
        cover:"1ddPPTys.jpg",
        imgs:["i1.jpg"],
        title:"1点点虎年PPT元素",
        cate:"illustration",
        desc:"1点点虎年PPT元素"
    },
    {
        id:39,
        cover:"1ddbqb.jpg",
        imgs:["i1.jpg"],
        title:"1点点表情包",
        cate:"illustration",
        desc:"1点点表情包"
    },
    {
        id:40,
        cover:"1ddhz.jpg",
        imgs:["i1.jpg"],
        title:"1点点徽章插画",
        cate:"illustration",
        desc:"1点点徽章插画"
    },
    {
        id:41,
        cover:"qsfcxcxj.jpg",
        imgs:["c1.jpg"],
        title:"七色纺初夏出【型】季活动",
        cate:"retailMaterial",
        desc:"七色纺初夏出【型】季活动"
    },
    {
        id:42,
        cover:"qsfxrjj.jpg",
        imgs:["c1.jpg"],
        title:"七色纺夏日居家活动",
        cate:"retailMaterial",
        desc:"七色纺夏日居家活动"
    }
];